# Generated by Django 3.1.2 on 2020-10-16 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_ref', models.AutoField(primary_key=True, serialize=False)),
                ('book_date', models.DateField()),
                ('total_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_no', models.CharField(max_length=10)),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='airtrans.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='airtrans.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_no', models.AutoField(primary_key=True, serialize=False)),
                ('passenger_id', models.PositiveIntegerField()),
                ('passenger_name', models.CharField(max_length=50)),
                ('contact_data', models.EmailField(max_length=50)),
                ('book_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.booking')),
            ],
        ),
        migrations.CreateModel(
            name='TicketFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_condition', models.CharField(choices=[('1', 'Эконом класс'), ('2', 'Бизнес класс'), ('3', 'Первый класс')], max_length=1)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.flight')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.ticket')),
            ],
            options={
                'unique_together': {('ticket_no', 'flight_id')},
            },
        ),
        migrations.CreateModel(
            name='BoardingPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.ticketflight')),
            ],
        ),
    ]
